local keyMap = {
    [BongoInput.Key.A] = 'a',
    [BongoInput.Key.B] = 'b',
    [BongoInput.Key.C] = 'c',
    [BongoInput.Key.D] = 'd',
    [BongoInput.Key.E] = 'e',
    [BongoInput.Key.F] = 'f',
    [BongoInput.Key.G] = 'g',
    [BongoInput.Key.H] = 'h',
    [BongoInput.Key.I] = 'i',
    [BongoInput.Key.J] = 'j',
    [BongoInput.Key.K] = 'k',
    [BongoInput.Key.L] = 'l',
    [BongoInput.Key.M] = 'm',
    [BongoInput.Key.N] = 'n',
    [BongoInput.Key.O] = 'o',
    [BongoInput.Key.P] = 'p',
    [BongoInput.Key.Q] = 'q',
    [BongoInput.Key.R] = 'r',
    [BongoInput.Key.S] = 's',
    [BongoInput.Key.T] = 't',
    [BongoInput.Key.U] = 'u',
    [BongoInput.Key.V] = 'v',
    [BongoInput.Key.W] = 'w',
    [BongoInput.Key.X] = 'x',
    [BongoInput.Key.Y] = 'y',
    [BongoInput.Key.Z] = 'z',

    [BongoInput.Key.Num0] = '0',
    [BongoInput.Key.Num1] = '1',
    [BongoInput.Key.Num2] = '2',
    [BongoInput.Key.Num3] = '3',
    [BongoInput.Key.Num4] = '4',
    [BongoInput.Key.Num5] = '5',
    [BongoInput.Key.Num6] = '6',
    [BongoInput.Key.Num7] = '7',
    [BongoInput.Key.Num8] = '8',
    [BongoInput.Key.Num9] = '9',

    [BongoInput.Key.LeftBracket] = '[',
    [BongoInput.Key.RightBracket] = ']',
    [BongoInput.Key.Comma] = ',',
    [BongoInput.Key.Period] = '.',
    [BongoInput.Key.Slash] = '/',
    [BongoInput.Key.Dash] = '-',
    [BongoInput.Key.Equal] = '=',
}
